services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-despesas-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: api_despesas
      DB_USERNAME: root
      DB_PASSWORD: rootpass
    networks:
      - api-despesas-network

  db:
    image: mysql:5.7
    container_name: api-despesas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_despesas
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "33066:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - api-despesas-network

volumes:
  dbdata:

networks:
  api-despesas-network:
    driver: bridge